### PR TITLE
Last location only

### PR DESCRIPTION
**Pull request by Jorn08**
Added Config option to only spawn at the last location and prevents the location menu from popping up. Still needs some testing regarding spawning at apartments.

### CODE REVIEW

**Review by i-kulgu — APPROVED** [review]
LGTM

**Comment by Doxria** [comment]
LGTM

**Review by Doxria — APPROVED** [review]
LGTM 

Tested

**Comment by Twikii** [comment]
I also tested, locally it's perfect, on a production server, an error occurs from time to time on a random player.

`[script:qb-multichara] SCRIPT ERROR: @qb-multicharacter/server/main.lua:99: attempt to index a nil value`

**Review by Irishstevie — APPROVED** [review]
This works fine.... And good to go

**Pull request closed without merging**
