### PR TITLE
added citizenid to driver license

### PR DESCRIPTION
**Pull request by GeekHamza1**

### CODE REVIEW

**Comment by milotiro95** [comment]
I tried but not working for me.

**Comment by GeekHamza1** [comment]
> I tried but not working for me.

hey you should add it to also to you qb-cityhall and qb-inventory ,

**Comment by milotiro95** [comment]
Hey. Can you link the 2 others pull requests here ? I found the modification of qb-cityhall but not for qb-inventory.

**Comment by milotiro95** [comment]
Nop I'm using the master branch qb-idcard is integrate into like qb-logs.

**Comment by tom-osborne** [comment]
This does not work on it's own. Closing this as not planned.

Please add the required changes to other resources and link their PR's if a PR has other dependencies.

Thanks.

**Pull request closed without merging**
